default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: just_remote_development

test:
  <<: *default
  database: just_remote_test

production:
  <<: *default
  database: just_remote_production
  username: 
  password: 