default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  timeout: 5000
  host: <%= ENV['POSTGRES_HOST']%>


development:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE'] %>


test:
  <<: *default
  database: <%= ENV['POSTGRES_DATABASE_TEST'] %>


production:
  <<: *default
  database: db/production.postgresql
